apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-aas-service
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: provider-aas-service
  template:
    metadata:
      labels:
        app: provider-aas-service
    spec:
      containers:
      - image: cxtsiacr.azurecr.io/backend/simple-aas-adapter:catenax-at-home-latest
        imagePullPolicy: Always
        name: provider-aas-service
        ports:
        - containerPort: 4244 # API
        - containerPort: 8090 # JDB
      imagePullSecrets:
      - name: cx-registry
---
apiVersion: v1
kind: Service
metadata:
  name: provider-aas-service
spec:
  type: ClusterIP
  ports:
  - port: 4244
    name: api
    targetPort: 4244
  selector:
    app: provider-aas-service
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: provider-aas-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/x-forwarded-prefix: "/provider"
spec:
  tls:
    - hosts:
        - catenax-at-home.mx.k8scluster.de
      secretName: catenax-at-home-secret
  rules:
    - host: catenax-at-home.mx.k8scluster.de
      http:
        paths:
          - path: /provider(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: provider-aas-service
                port:
                  number: 4244
